# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2.4.2

    - name: Install required packages
      run: |
        sudo apt install antlr4
        sudo apt install libantlr4-runtime-dev
        sudo apt install default-jdk
        
    - name: Make gcc files
      run: |
        cd ./compiler
        ./runmake_ubuntu.sh
        cd ../
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Start tests
      run: |
        python ./tests/ifcc-test.py ./tests/testfiles
